const AlgoActionsTypes = {
    SET_CURRENT_SORTED : "SET_CURRENT_SORTED",
    SET_CURRENT_SWAPPERS :"SET_CURRENT_SWAPPERS",
    SET_RUNNING : "SET_RUNNING",
    SET_ARRAY : "SET_ARRAY",
    SET_ALGO : "SET_ALGO",
    SET_CURRENT_BUBBLE_ITEMS:"SET_CURRENT_BUBBLE_ITEMS"
}

export default AlgoActionsTypes;